add campaign-info.txt and check for missing mysql_connect.inc.php file in build script
Signed-off-by: Sebastian Krzyszkowiak <dos@dosowisko.net>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,6 +2,12 @@
 set -e
 shopt -s nullglob
 
+if [ ! -f assets/mysql_connect.inc.php ]; then
+echo "Missing file assets/mysql_connect.inc.php!"
+echo "Aborting..."
+exit 1
+fi
+
 rm -rf output
 mkdir -p output
 
